Task6.PhoneBook.test
DodoKingBurger/CSharpEducation pull request #4
Opened 2024-10-16 11:45 UTC by DodoKingBurger

Просыпаются утром программист с женой, за окном – грустный серый осенний день.
Жена:
- Какой сегодня серый день...
Программист:
- Да. Палитра слетела…

Стоит программист возле окна – закрывает, открывает. Закрывает, открывает. Подходит второй и спрашивает:
- Что ты делаешь?
- Ну, прикинь: закрыть могу, открыть могу, а свернуть – не могу!

2024-10-22 05:54 UTC, Dezodemius requested changes

2024-10-22 05:54 UTC, Dezodemius commented on Phonebook.Test/Phonebook.Tests.cs
> +		[TestCase("B58B3851-9F5F-4CB8-BC0B-64BB42794EA7")]
как бы ок, но TestCase лучше применять, когда нужно разные текст-кейсы для одного теста делать. То есть, ты ставишь несколько атрибутов друг над другом. Тут надо либо переделать на Test, либо поискать как можно сгруппировать тесты в один метод, чтобы можно было TestCase-ы навесить

2024-10-23 04:14 UTC, DodoKingBurger commented on Phonebook.Test/Phonebook.Tests.cs
> +		[TestCase("B58B3851-9F5F-4CB8-BC0B-64BB42794EA7")]
Решил переделать в Test, закинул изменения

Счастье - это когда ты просыпаешься и высыпаешься одновременно.

2024-10-24 05:03 UTC, Dezodemius approved these changes

2024-10-26 20:34 UTC, merged